// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: shop/v1/product.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	OrderManagerService_GetOrder_FullMethodName = "/shop.v1.OrderManagerService/GetOrder"
)

// OrderManagerServiceClient is the client API for OrderManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderManagerServiceClient interface {
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
}

type orderManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderManagerServiceClient(cc grpc.ClientConnInterface) OrderManagerServiceClient {
	return &orderManagerServiceClient{cc}
}

func (c *orderManagerServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, OrderManagerService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderManagerServiceServer is the server API for OrderManagerService service.
// All implementations must embed UnimplementedOrderManagerServiceServer
// for forward compatibility
type OrderManagerServiceServer interface {
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	mustEmbedUnimplementedOrderManagerServiceServer()
}

// UnimplementedOrderManagerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderManagerServiceServer struct {
}

func (UnimplementedOrderManagerServiceServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderManagerServiceServer) mustEmbedUnimplementedOrderManagerServiceServer() {}

// UnsafeOrderManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderManagerServiceServer will
// result in compilation errors.
type UnsafeOrderManagerServiceServer interface {
	mustEmbedUnimplementedOrderManagerServiceServer()
}

func RegisterOrderManagerServiceServer(s grpc.ServiceRegistrar, srv OrderManagerServiceServer) {
	s.RegisterService(&OrderManagerService_ServiceDesc, srv)
}

func _OrderManagerService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderManagerServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderManagerService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderManagerServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderManagerService_ServiceDesc is the grpc.ServiceDesc for OrderManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shop.v1.OrderManagerService",
	HandlerType: (*OrderManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrder",
			Handler:    _OrderManagerService_GetOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shop/v1/product.proto",
}
